### ISSUE TITLE
点击通知栏的事件没有监听到

### ISSUE THREAD

**Issue by zhangmingnjun** [magicwing/react-native-jmessage#1]
点击通知栏，没有进入app，希望补充这样的代码，实现这个功能

**Comment by magicwing** [comment]
android的启动需要加入的代码和位置如下，ios的例子应该已经有了。

public class MainActivity extends ReactActivity {

    final String TAG = "MainActivity";
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        ......
        getReactNativeHost().getReactInstanceManager().addReactInstanceEventListener(new ReactInstanceManager.ReactInstanceEventListener() {
            @Override
            public void onReactContextInitialized(ReactContext context) {
                ......
               // 点击启动开始代码
                Bundle mBundle = MainActivity.this.getIntent().getExtras();
                if (mBundle == null) return;
                Log.d(TAG, "启动携带参数");
                if (mBundle.getString("ReactNativeAction") == JPushInterface.ACTION_NOTIFICATION_OPENED) {
                    WritableMap map = Arguments.createMap();
                    map.putString("alertContent", mBundle.getString("alertContent"));
                    map.putString("extras", mBundle.getString("extras"));
                    context.getJSModule(DeviceEventManagerModule.RCTDeviceEventEmitter.class).emit("openNotification", map);
                }
            }
        });

        super.onCreate(savedInstanceState);
    }
...
}

**Comment by zhangmingnjun** [comment]
我是在你监听接收消息的地方，加了一个通知栏点击事件的监听，然后在index.js文件里调用。但是不成功。我把我的修改贴在下面，你帮我看一下吧。
![image](https://user-images.githubusercontent.com/20589092/26915847-48cebada-4c5a-11e7-8967-fc207bf155f6.png)

**Comment by magicwing** [comment]
我的代码不是已经有了吗
点击消息通过intent传参方式启动你的app的mainactivity
![1](https://user-images.githubusercontent.com/7157683/26916133-9837b5bc-4c5b-11e7-8cbb-851f2f52b124.jpg)
在mainactivity中判断启动参数ReactNativeAction 的值是否是点击消息启动，然后提交给监听事件
![2](https://user-images.githubusercontent.com/7157683/26916142-a2d4dbf8-4c5b-11e7-9781-bca0561fca79.jpg)

**Comment by zhangmingnjun** [comment]
我是昨天新安装的这个插件，你是不是没把代码提交啊

**Comment by zhangmingnjun** [comment]
要不我重新安装一下这个插件，或者你来补充一个完整的文档。谢谢了。

我的qq：845533876，麻烦加一下吧，便于请教问题

**Comment by magicwing** [comment]
有啊

![default](https://user-images.githubusercontent.com/7157683/26916541-598c39ee-4c5d-11e7-81ee-7c0e4eb8d1ec.png)

**Comment by zhangmingnjun** [comment]
确实看到了，你提交的代码，但是我安装的不是这样的。估计是你提交的时候，版本没更新吧。我一会儿直接下载这个插件去替换我本地的插件。
另外，我需要在项目跟目录下的android处做什么修改呢？

**Comment by zhangmingnjun** [comment]
我的安装命令是： npm i react-native-jmessage --save，然后执行react-native link去配置，最后在rn项目里初始化jmessage，调用、监听收发消息。

现在已经在下载你提供的插件，准备替换我本地的。rn项目根目录下的android应该也有修改吧，希望得到你的帮助，尽快完成修改，不尽感激！！谢谢

**Comment by magicwing** [comment]
npm i github:magicwing/react-native-jmessage
android的在mainactivity中添加下图代码
[https://user-images.githubusercontent.com/7157683/26916142-a2d4dbf8-4c5b-11e7-9781-bca0561fca79.jpg](url)

**Comment by zhangmingnjun** [comment]
直接替换后，编译的时候报了好多错。。。
![image](https://user-images.githubusercontent.com/20589092/26918895-545206b2-4c66-11e7-98ad-8d0c993ebbe0.png)
现在我把这个插件下载了，按照你的方式来试一下。
另外，你能不能给我发一下mainactivity里的代码，里面的import什么的，我也想看看有什么

**Comment by magicwing** [comment]
你把原先的卸载掉，用这个npm i github:magicwing/react-native-jmessage github:magicwing/jpush-react-native 安装，你上面报错很明显是lib下面的sdk没有或者版本不对，android的mainactivity代码上面已经发过了，参照4搂第二图。我项目是rn0.37，jpush和jmessage全部都是用我自己修改过的（github:magicwing/jpush-react-native、github:magicwing/react-native-jmessage），2个插件是共享lib的和共享部分代码的。大致就是这样了，代码什么的公司项目东西只能到这里了，你自己努力一下吧。
